/**
 * Example: 'PST' => 'America/Los_Angeles'
 */
export function convertTimeZone(abbrOfTimeZone: string) {
  return new Intl.DateTimeFormat('en-GB', {
    timeZone: abbrOfTimeZone,
  }).resolvedOptions().timeZone;
}

/**
 * Copy from https://www.timejones.com/TimeZoneAbbreviations
 */
export const TimeZones = [
  {
    abbreviation: 'EST',
    description: 'Eastern Standard Time',
    offset: 'UTC−05:00',
  },
  {
    abbreviation: 'CST',
    description: 'Central Standard Time',
    offset: 'UTC−06:00',
  },
  {
    abbreviation: 'CDT',
    description: 'Central Daylight Time',
    offset: 'UTC-05:00',
  },
  {
    abbreviation: 'MST',
    description: 'Mountain Standard Time',
    offset: 'UTC−07:00',
  },
  {
    abbreviation: 'PST',
    description: 'Pacific Standard Time',
    offset: 'UTC−08:00',
  },
  {
    abbreviation: 'EDT',
    description: 'Eastern Daylight Time',
    offset: 'UTC−04:00',
  },
  {
    abbreviation: 'MDT',
    description: 'Mountain Daylight Time',
    offset: 'UTC−06:00',
  },
  {
    abbreviation: 'PDT',
    description: 'Pacific Daylight Time',
    offset: 'UTC−07:00',
  },
  {
    abbreviation: 'ADT',
    description: 'Atlantic Daylight Time',
    offset: 'UTC−03:00',
  },
  {
    abbreviation: 'AKDT',
    description: 'Alaska Daylight Time',
    offset: 'UTC−08:00',
  },
  {
    abbreviation: 'AKST',
    description: 'Alaska Standard Time',
    offset: 'UTC−09:00',
  },
  {
    abbreviation: 'HAST',
    description: 'Hawaii Aleutian Standard Time',
    offset: 'UTC−10:00',
  },
  {
    abbreviation: 'HADT',
    description: 'Hawaii Aleutian Daylight Time',
    offset: 'UTC−09:00',
  },
  {
    abbreviation: 'AST',
    description: 'Atlantic Standard Time',
    offset: 'UTC−04:00',
  },
  {
    abbreviation: 'EGST',
    description: 'Eastern Greenland Summer Time',
    offset: 'UTC+00:00',
  },
  {
    abbreviation: 'EGT',
    description: 'Eastern Greenland Time',
    offset: 'UTC−01:00',
  },
  {
    abbreviation: 'WGST',
    description: 'Western Greenland Summer Time',
    offset: 'UTC-02:00',
  },
  {
    abbreviation: 'WGT',
    description: 'Western Greenland Time',
    offset: 'UTC−03:00',
  },
  {
    abbreviation: 'NDT',
    description: 'Newfoundland Daylight Time	UTC',
    offset: '−02:30',
  },
  {
    abbreviation: 'NST',
    description: 'Newfoundland Standard Time	UTC',
    offset: '−03:30',
  },
  {
    abbreviation: 'PMDT',
    description: 'Saint Pierre and Miquelon Daylight time',
    offset: 'UTC−02:00',
  },
  {
    abbreviation: 'PMST',
    description: 'Saint Pierre and Miquelon Standard Time',
    offset: 'UTC−03:00',
  },
  {abbreviation: 'CST', description: 'Cuba Standard Time', offset: 'UTC-05:00'},
  {abbreviation: 'CDT', description: 'Cuba Daylight Time', offset: 'UTC-04:00'},
  {abbreviation: 'ART', description: 'Argentina Time', offset: 'UTC−03:00'},
  {abbreviation: 'ACT', description: 'Acre Time', offset: 'UTC−05:00'},
  {abbreviation: 'ECT', description: 'Ecuador Time', offset: 'UTC−05:00'},
  {
    abbreviation: 'ECT',
    description: 'Eastern Caribbean Time',
    offset: 'UTC−04:00',
  },
  {
    abbreviation: 'FKT',
    description: 'Falkland Islands Time',
    offset: 'UTC−04:00',
  },
  {abbreviation: 'BOT', description: 'Bolivia Time', offset: 'UTC−04:00'},
  {abbreviation: 'BRT', description: 'Brasilia Time', offset: 'UTC−03:00'},
  {
    abbreviation: 'CLT',
    description: 'Chile Standard Time',
    offset: 'UTC−04:00',
  },
  {abbreviation: 'COT', description: 'Colombia Time', offset: 'UTC−05:00'},
  {
    abbreviation: 'FKST',
    description: 'Falkland Islands Standard Time',
    offset: 'UTC−03:00',
  },
  {
    abbreviation: 'FNT',
    description: 'Fernando de Noronha Time',
    offset: 'UTC−02:00',
  },
  {abbreviation: 'GFT', description: 'French Guiana Time', offset: 'UTC−03:00'},
  {abbreviation: 'GYT', description: 'Guyana Time', offset: 'UTC−04:00'},
  {abbreviation: 'PET', description: 'Peru Time', offset: 'UTC−05:00'},
  {
    abbreviation: 'PYST',
    description: 'Paraguay Summer Time',
    offset: 'UTC−03:00',
  },
  {abbreviation: 'PYT', description: 'Paraguay Time', offset: 'UTC−04:00'},
  {abbreviation: 'SRT', description: 'Suriname Time', offset: 'UTC−03:00'},
  {
    abbreviation: 'UYT',
    description: 'Uruguay Standard Time',
    offset: 'UTC−03:00',
  },
  {
    abbreviation: 'VET',
    description: 'Venezuelan Standard Time',
    offset: 'UTC−04:30',
  },
  {
    abbreviation: 'CAT',
    description: 'Central Africa Time',
    offset: 'UTC+02:00',
  },
  {abbreviation: 'CVT', description: 'Cape Verde Time', offset: 'UTC−01:00'},
  {abbreviation: 'EAT', description: 'East Africa Time', offset: 'UTC+03:00'},
  {abbreviation: 'MUT', description: 'Mauritius Time', offset: 'UTC+04:00'},
  {abbreviation: 'RET', description: 'Réunion Time', offset: 'UTC+04:00'},
  {
    abbreviation: 'SAST',
    description: 'South African Standard Time',
    offset: 'UTC+02:00',
  },
  {abbreviation: 'SCT', description: 'Seychelles Time', offset: 'UTC+04:00'},
  {
    abbreviation: 'WAST',
    description: 'West Africa Summer Time',
    offset: 'UTC+02:00',
  },
  {abbreviation: 'WAT', description: 'West Africa Time', offset: 'UTC+01:00'},
  {
    abbreviation: 'GMT',
    description: 'Greenwich Mean Time',
    offset: 'UTC+00:00',
  },
  {
    abbreviation: 'BST',
    description: 'British Summer Time',
    offset: 'UTC+01:00',
  },
  {
    abbreviation: 'CEST',
    description: 'Central European Summer Time',
    offset: 'UTC+02:00',
  },
  {
    abbreviation: 'CET',
    description: 'Central European Time',
    offset: 'UTC+01:00',
  },
  {
    abbreviation: 'EEST',
    description: 'Eastern European Summer Time',
    offset: 'UTC+03:00',
  },
  {
    abbreviation: 'EET',
    description: 'Eastern European Time',
    offset: 'UTC+02:00',
  },
  {
    abbreviation: 'FET',
    description: 'Further-eastern European Time,MinskTime',
    offset: 'UTC+03:00',
  },
  {abbreviation: 'MSK', description: 'Moscow Time', offset: 'UTC+03:00'},
  {
    abbreviation: 'WEST',
    description: 'Western European Summer Time',
    offset: 'UTC+01:00',
  },
  {
    abbreviation: 'WET',
    description: 'Western European Time',
    offset: 'UTC+00:00',
  },
  {abbreviation: 'AFT', description: 'Afghanistan Time', offset: 'UTC+04:30'},
  {abbreviation: 'AMT', description: 'Armenia Time', offset: 'UTC+04:00'},
  {abbreviation: 'ALMT', description: 'Almaty Time', offset: 'UTC+06:00'},
  {
    abbreviation: 'AST',
    description: 'Arabia Standard Time',
    offset: 'UTC+03:00',
  },
  {abbreviation: 'AZT', description: 'Azerbaijan Time', offset: 'UTC+04:00'},
  {abbreviation: 'BDT', description: 'Bangladesh Time', offset: 'UTC+06:00'},
  {
    abbreviation: 'BNT',
    description: 'Brunei Darussalam Time',
    offset: 'UTC+08:00',
  },
  {abbreviation: 'BTT', description: 'Bhutan Time', offset: 'UTC+06:00'},
  {
    abbreviation: 'CCT',
    description: 'Cocos (Keeling) Islands Time',
    offset: 'UTC+6:30',
  },
  {abbreviation: 'CHOT', description: 'Choibalsan Time', offset: 'UTC+08:00'},
  {
    abbreviation: 'CHST',
    description: 'Chamorro Standard Time',
    offset: 'UTC+10:00',
  },
  {
    abbreviation: 'CST',
    description: 'China Standard Time',
    offset: 'UTC+08:00',
  },
  {
    abbreviation: 'GET',
    description: 'Georgia Standard Time',
    offset: 'UTC+04:00',
  },
  {abbreviation: 'GST', description: 'Gulf Standard Time', offset: 'UTC+04:00'},
  {abbreviation: 'HKT', description: 'Hong Kong Time', offset: 'UTC+08:00'},
  {abbreviation: 'HOVT', description: 'Khovd Time', offset: 'UTC+07:00'},
  {abbreviation: 'ICT', description: 'Indochina Time', offset: 'UTC+07:00'},
  {
    abbreviation: 'IDT',
    description: 'Israel Daylight Time',
    offset: 'UTC+03:00',
  },
  {
    abbreviation: 'IRDT',
    description: 'Iran Daylight Time',
    offset: 'UTC+04:30',
  },
  {abbreviation: 'IRKT', description: 'Irkutsk Time', offset: 'UTC+08:00'},
  {
    abbreviation: 'IRST',
    description: 'Iran Standard Time',
    offset: 'UTC+03:30',
  },
  {
    abbreviation: 'IST',
    description: 'Indian Standard Time',
    offset: 'UTC+05:30',
  },
  {
    abbreviation: 'IST',
    description: 'Israel Standard Time',
    offset: 'UTC+02:00',
  },
  {
    abbreviation: 'JST',
    description: 'Japan Standard Time',
    offset: 'UTC+09:00',
  },
  {abbreviation: 'KGT', description: 'Kyrgyzstan time', offset: 'UTC+06:00'},
  {abbreviation: 'KRAT', description: 'Krasnoyarsk Time', offset: 'UTC+07:00'},
  {
    abbreviation: 'KST',
    description: 'Korea Standard Time',
    offset: 'UTC+09:00',
  },
  {abbreviation: 'MAGT', description: 'Vladivostok Time', offset: 'UTC+10:00'},
  {
    abbreviation: 'MHT',
    description: 'Marshall Islands Time',
    offset: 'UTC+12:00',
  },
  {abbreviation: 'MMT', description: 'Myanmar Time', offset: 'UTC+06:30'},
  {abbreviation: 'MVT', description: 'Maldives Time', offset: 'UTC+05:00'},
  {abbreviation: 'MYT', description: 'Malaysia Time', offset: 'UTC+08:00'},
  {abbreviation: 'NPT', description: 'Nepal Time', offset: 'UTC+05:45'},
  {abbreviation: 'OMST', description: 'Omsk Time', offset: 'UTC+06:00'},
  {abbreviation: 'ORAT', description: 'Oral Time', offset: 'UTC+05:00'},
  {abbreviation: 'PETT', description: 'Kamchatka Time', offset: 'UTC+12:00'},
  {
    abbreviation: 'PGT',
    description: 'Papua New Guinea Time',
    offset: 'UTC+10:00',
  },
  {abbreviation: 'PHT', description: 'Philippines Time', offset: 'UTC+08:00'},
  {
    abbreviation: 'PKT',
    description: 'Pakistan Standard Time',
    offset: 'UTC+05:00',
  },
  {abbreviation: 'PWT', description: 'Palau Time', offset: 'UTC+09:00'},
  {
    abbreviation: 'SAKT',
    description: 'Sakhalin Island time',
    offset: 'UTC+11:00',
  },
  {abbreviation: 'SGT', description: 'Singapore Time', offset: 'UTC+08:00'},
  {
    abbreviation: 'SRET',
    description: 'Srednekolymsk Time',
    offset: 'UTC+11:00',
  },
  {
    abbreviation: 'SLST',
    description: 'Sri Lanka Standard Time',
    offset: 'UTC+05:30',
  },
  {abbreviation: 'TJT', description: 'Tajikistan Time', offset: 'UTC+05:00'},
  {abbreviation: 'TLT', description: 'Timor Leste Time', offset: 'UTC+09:00'},
  {abbreviation: 'TMT', description: 'Turkmenistan Time', offset: 'UTC+05:00'},
  {abbreviation: 'ULAT', description: 'Ulaanbaatar Time', offset: 'UTC+08:00'},
  {abbreviation: 'UZT', description: 'Uzbekistan Time', offset: 'UTC+05:00'},
  {abbreviation: 'VLAT', description: 'Vladivostok Time', offset: 'UTC+10:00'},
  {
    abbreviation: 'WIT',
    description: 'Western Indonesian Time',
    offset: 'UTC+07:00',
  },
  {
    abbreviation: 'WIB',
    description: 'Waktu Indonesia Barat',
    offset: 'UTC+07:00',
  },
  {abbreviation: 'YAKT', description: 'Yakutsk Time', offset: 'UTC+09:00'},
  {
    abbreviation: 'ACDT',
    description: 'Australian Central Daylight Savings Time',
    offset: 'UTC+10:30',
  },
  {
    abbreviation: 'ACST',
    description: 'Australian Central Standard Time',
    offset: 'UTC+09:30',
  },
  {
    abbreviation: 'AEDT',
    description: 'Australian Eastern Daylight Savings Time',
    offset: 'UTC+11:00',
  },
  {
    abbreviation: 'AEST',
    description: 'Australian Eastern Standard Time',
    offset: 'UTC+10:00',
  },
  {
    abbreviation: 'AWDT',
    description: 'Australian Western Daylight Time',
    offset: 'UTC+09:00',
  },
  {
    abbreviation: 'AWST',
    description: 'Australian Western Standard Time',
    offset: 'UTC+08:00',
  },
  {abbreviation: 'CKT', description: 'Cook Islands Time', offset: 'UTC-10:00'},
  {
    abbreviation: 'CXT',
    description: 'Christmas Island Time',
    offset: 'UTC+07:00',
  },
  {abbreviation: 'FJT', description: 'Fiji Time', offset: 'UTC+12:00'},
  {
    abbreviation: 'GILT',
    description: 'Gilbert Islands Time',
    offset: 'UTC+12:00',
  },
  {
    abbreviation: 'LHST',
    description: 'Lord Howe Standard Time',
    offset: 'UTC+10:30',
  },
  {abbreviation: 'NCT', description: 'New Caledonia Time', offset: 'UTC+11:00'},
  {abbreviation: 'LHST', description: 'Norfolk Time', offset: 'UTC+11:30'},
  {abbreviation: 'NRT', description: 'Nauru Time', offset: 'UTC+12:00'},
  {abbreviation: 'NUT', description: 'Niue Time', offset: 'UTC-11:00'},
  {
    abbreviation: 'NZST',
    description: 'New Zealand Standard Time',
    offset: 'UTC+12:00',
  },
  {
    abbreviation: 'PONT',
    description: 'Pohnpei Standard Time',
    offset: 'UTC+10:00',
  },
  {
    abbreviation: 'SBT',
    description: 'Solomon Islands Time',
    offset: 'UTC+11:00',
  },
  {
    abbreviation: 'SST',
    description: 'Samoa Standard Time',
    offset: 'UTC-11:00',
  },
  {abbreviation: 'VUT', description: 'Vanuatu Time', offset: 'UTC+11:00'},
  {abbreviation: 'TAHT', description: 'Tahiti Time', offset: 'UTC-10:00'},
  {abbreviation: 'TVT', description: 'Tuvalu Time', offset: 'UTC+12:00'},
  {abbreviation: 'WFT', description: 'Wallis and Futuna', offset: 'UTC+12:00'},
  {
    abbreviation: 'WSST',
    description: 'Western Samoa Summer Time',
    offset: 'UTC+14:00',
  },
];
