import { MODULES_CONFIG_TS, MODULES_MODULE_TS } from "../constants/paths";
import { ModuleMeta, MODULES } from "../modules-catalog";
import { IssueBag, reportIssue } from "../lib/issues";
import { readModuleSettings } from "../lib/module-settings";
import { Sink } from "../lib/sink";

const DO_NOT_EDIT_HEADER = `// THIS FILE IS GENERATED BY @devbie/newbie-cli. DO NOT EDIT.
// Run 'newbie install' to regenerate this file.

`;

const EMPTY_MODULE_TEMPLATE = `${DO_NOT_EDIT_HEADER}import {Global, Module} from '@nestjs/common';

@Global()
@Module({
  imports: [],
})
export class MicroservicesModule {}
`;

const EMPTY_CONFIG_TEMPLATE = `${DO_NOT_EDIT_HEADER}import {registerAs} from '@nestjs/config';

export default registerAs('microservices', () => ({}));
`;

function moduleTemplate(modules: ModuleMeta[]): string {
  const hasConfigService = modules.length > 0;
  const importCode = [
    `import {Global, Module} from '@nestjs/common';`,
    hasConfigService
      ? `import MicroservicesConfiguration from './microservices.config';\nimport {ConfigModule} from '@nestjs/config';`
      : "",
    ...modules.map((meta) => meta.importCode),
  ]
    .filter(Boolean)
    .join("\n");

  const importModuleNames = [
    hasConfigService
      ? `ConfigModule.forRoot({load: [MicroservicesConfiguration], isGlobal: true})`
      : "",
    ...modules.map((meta) => meta.moduleNames),
  ]
    .filter(Boolean)
    .join(",\n    ");

  return `${DO_NOT_EDIT_HEADER}${importCode}

@Global()
@Module({
  imports: [
    ${importModuleNames}
  ],
})
export class MicroservicesModule {}
`;
}

function configTemplate(configs: Record<string, unknown>): string {
  // The settings store runtime expressions as plain strings ("process.env.X");
  // unwrap the quotes so they become real TS expressions in the generated file.
  const body = JSON.stringify(configs, null, 2)
    .replace(/("|')(process.*?)\1/g, "$2")
    .replace(/("|')(bool\(process.*?)\1/g, "$2")
    .replace(/("|')(int\(process.*?)\1/g, "$2");

  return `${DO_NOT_EDIT_HEADER}import {registerAs} from '@nestjs/config';
import {bool, int} from '@devbie/newbie';

export default registerAs('microservices', () => (${body}));
`;
}

export async function assembleNestJsModules(params: {
  cwd: string;
  sink: Sink;
  issues: IssueBag;
  enabledNames: string[];
}): Promise<void> {
  const { cwd, sink, issues, enabledNames } = params;
  const enabled = enabledNames
    .map((name) => MODULES[name])
    .filter((meta): meta is ModuleMeta => Boolean(meta));

  await sink.writeText(
    MODULES_MODULE_TS,
    enabled.length > 0 ? moduleTemplate(enabled) : EMPTY_MODULE_TEMPLATE,
  );

  let configs: Record<string, unknown> = {};
  for (const meta of enabled) {
    const settings = await readModuleSettings(cwd, meta);
    if (settings === null) {
      reportIssue(
        issues,
        sink,
        `Missing ${meta.key}.settings.json; its config-service entries were skipped.`,
      );
      continue;
    }
    configs = { ...configs, ...(settings["config-service"] ?? {}) };
  }

  await sink.writeText(
    MODULES_CONFIG_TS,
    Object.keys(configs).length > 0
      ? configTemplate(configs)
      : EMPTY_CONFIG_TEMPLATE,
  );

  // Formatting failure is fatal (legacy CLI swallowed the non-zero exit).
  await sink.run(
    "npx",
    ["prettier", "--write", MODULES_MODULE_TS, MODULES_CONFIG_TS],
    "prettier generated module files",
  );
}
