import { MODULES_CONFIG_TS, MODULES_MODULE_TS } from "../constants/paths";
import { moduleImportLine, ModuleManifest } from "../core/module-manifest";
import { IssueBag, reportIssue } from "../lib/issues";
import { readInstalledManifest } from "../lib/module-install";
import { Sink } from "../lib/sink";

const DO_NOT_EDIT_HEADER = `// THIS FILE IS GENERATED BY @devbie/newbie-cli. DO NOT EDIT.
// Run 'newbie install' to regenerate this file.

`;

const EMPTY_MODULE_TEMPLATE = `${DO_NOT_EDIT_HEADER}import {Global, Module} from '@nestjs/common';

@Global()
@Module({
  imports: [],
})
export class ModulesModule {}
`;

const EMPTY_CONFIG_TEMPLATE = `${DO_NOT_EDIT_HEADER}import {registerAs} from '@nestjs/config';

export default registerAs('modules', () => ({}));
`;

function moduleTemplate(
  entries: { key: string; manifest: ModuleManifest }[],
): string {
  const hasConfigService = entries.length > 0;
  const importCode = [
    `import {Global, Module} from '@nestjs/common';`,
    hasConfigService
      ? `import ModulesConfiguration from './modules.config';\nimport {ConfigModule} from '@nestjs/config';`
      : "",
    ...entries.map(({ key, manifest }) => moduleImportLine(key, manifest)),
  ]
    .filter(Boolean)
    .join("\n");

  const importModuleNames = [
    hasConfigService
      ? `ConfigModule.forRoot({load: [ModulesConfiguration], isGlobal: true})`
      : "",
    ...entries.map(({ manifest }) => manifest.module.className),
  ]
    .filter(Boolean)
    .join(",\n    ");

  return `${DO_NOT_EDIT_HEADER}${importCode}

@Global()
@Module({
  imports: [
    ${importModuleNames}
  ],
})
export class ModulesModule {}
`;
}

function configTemplate(configs: Record<string, unknown>): string {
  // The manifest stores runtime expressions as plain strings ("process.env.X");
  // unwrap the quotes so they become real TS expressions in the generated file.
  const body = JSON.stringify(configs, null, 2)
    .replace(/("|')(process.*?)\1/g, "$2")
    .replace(/("|')(bool\(process.*?)\1/g, "$2")
    .replace(/("|')(int\(process.*?)\1/g, "$2");

  return `${DO_NOT_EDIT_HEADER}import {registerAs} from '@nestjs/config';
import {bool, int} from '@devbie/newbie';

export default registerAs('modules', () => (${body}));
`;
}

export async function assembleNestJsModules(params: {
  cwd: string;
  sink: Sink;
  issues: IssueBag;
  enabledKeys: string[];
}): Promise<void> {
  const { cwd, sink, issues, enabledKeys } = params;

  const entries: { key: string; manifest: ModuleManifest }[] = [];
  for (const key of enabledKeys) {
    const manifest = await readInstalledManifest(cwd, key);
    if (manifest === null) {
      reportIssue(
        issues,
        sink,
        `Missing newbie.module.json for '${key}'; it was skipped in the NestJS module wiring.`,
      );
      continue;
    }
    entries.push({ key, manifest });
  }

  await sink.writeText(
    MODULES_MODULE_TS,
    entries.length > 0 ? moduleTemplate(entries) : EMPTY_MODULE_TEMPLATE,
  );

  let configs: Record<string, unknown> = {};
  for (const { manifest } of entries) {
    configs = { ...configs, ...(manifest["config-service"] ?? {}) };
  }

  await sink.writeText(
    MODULES_CONFIG_TS,
    Object.keys(configs).length > 0
      ? configTemplate(configs)
      : EMPTY_CONFIG_TEMPLATE,
  );

  // Formatting failure is fatal (legacy CLI swallowed the non-zero exit).
  await sink.run(
    "npx",
    ["prettier", "--write", MODULES_MODULE_TS, MODULES_CONFIG_TS],
    "prettier generated module files",
  );
}
